language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - nightly

branches:
  only:
    - master

matrix:
  include:
    - php: 5.6
      env: SYMFONY_VERSION='2.6.*'
    - php: 5.6
      env: SYMFONY_VERSION='2.7.*'
    - php: 5.6
      env: SYMFONY_VERSION='2.8.*'
    - php: 7.1
      env: SYMFONY_VERSION='3.0.*'
    - php: 7.1
      env: SYMFONY_VERSION='3.1.*'
    - php: 7.1
      env: SYMFONY_VERSION='3.2.*'
    - php: 7.1
      env: SYMFONY_VERSION='3.3.*'
  fast_finish: true
  allow_failures:
    - php: nightly

before_script:
  - composer self-update
  - sh -c 'if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION; fi;'
  - composer update --prefer-source

script: phpunit
