language: php

php:
  - 7.1
  - 7.2
  - nightly

branches:
  only:
    - master

matrix:
  include:
    - php: 7.2
      env: SYMFONY_VERSION='3.3.*'
    - php: 7.2
      env: SYMFONY_VERSION='3.4.*'
    - php: 7.2
      env: SYMFONY_VERSION='3.4.*'
    - php: 7.2
      env: SYMFONY_VERSION='4.0.*'
  fast_finish: true
  allow_failures:
    - php: nightly

before_script:
  - composer self-update
  - sh -c 'if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION; fi;'
  - composer update --prefer-source

script: phpunit
